on:
  push:
    branches:
      - staging
      - trying
  pull_request:
    branches:
      - main

name: Continuous integration

jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust:
          - stable
          - beta
          - nightly
          - 1.71.1
    env:
      RUSTFLAGS: "-C target-cpu=native -C opt-level=3"
      ROARINGRS_BENCH_OFFLINE: "true"

    steps:
      - name: Checkout roaring-rs
        uses: actions/checkout@v2

      - name: Checkout benchmark datasets
        uses: actions/checkout@v2
        with:
          repository: "RoaringBitmap/real-roaring-datasets"
          path: "benchmarks/real-roaring-datasets"

      - name: Initialize rust toolchain
        uses: dtolnay/rust-toolchain@master
        if: matrix.rust != 'nightly'
        with:
          toolchain: ${{ matrix.rust }}
          components: rustfmt, clippy

      - name: Install nightly toolchain
        uses: actions-rs/toolchain@v1
        if: matrix.rust == 'nightly'
        with:
          toolchain: ${{ matrix.rust }}
          components: rustfmt, clippy, miri

      - name: Setup miri
        if: matrix.rust == 'nightly'
        run: cargo miri setup

      - name: Fetch
        run: cargo fetch

      - name: Build
        run: cargo build --all-targets

      - name: Check
        run: cargo clippy --all-targets -- -D warnings

      - name: Check formatting
        run: cargo fmt --all -- --check

      - name: Test
        working-directory: roaring
        run: cargo test --features serde

      - name: Test bit endian
        if: matrix.rust == 'nightly'
        run:
          cargo miri test --target s390x-unknown-linux-gnu --package roaring \
          --lib -- bitmap::serialization::test::test_from_lsb0_bytes

      - name: Test no default features
        working-directory: roaring
        run: cargo test --no-default-features

      - name: Test benchmarks
        working-directory: roaring
        run: cargo bench

      - name: SIMD test
        if: matrix.rust == 'nightly'
        working-directory: roaring
        run: cargo +nightly test --features simd

      - name: SIMD test benchmarks
        if: matrix.rust == 'nightly'
        working-directory: roaring
        run: cargo +nightly bench --features simd
